# playbooks/start_minecraft.yml
---
- name: Start Minecraft server in a new PowerShell window
  ansible.windows.win_shell: |
    Start-Process -FilePath "powershell.exe" -ArgumentList "-NoExit", "-Command", "cd 'C:/Users/simon/Minecraft'; java -Xmx1G -Xms1G -jar paper.jar --nogui"
