# initialize_server.yml
---
- name: Start the Minecraft server process and capture the process ID
  ansible.windows.win_shell: |
    $process = Start-Process -FilePath 'java' -ArgumentList '-Xmx1G -Xms1G -jar paper.jar --nogui' -WorkingDirectory 'C:/Users/simon/Minecraft' -PassThru
    $process.Id
  register: minecraft_process_id
  changed_when: true
  failed_when: minecraft_process_id.stdout is undefined

- name: Debug the Minecraft server process ID
  debug:
    msg: "Minecraft server process started with ID: {{ minecraft_process_id.stdout }}"
  when: minecraft_process_id.stdout is defined

- name: Wait for 60 seconds while the server runs using PowerShell
  ansible.windows.win_shell: |
    Start-Sleep -Seconds 60

- name: Check if the Minecraft server process is still running and terminate if needed
  ansible.windows.win_shell: |
    if (Get-Process -Id {{ minecraft_process_id.stdout }} -ErrorAction SilentlyContinue) {
        Stop-Process -Id {{ minecraft_process_id.stdout }} -Force
        Write-Output "Process terminated."
    } else {
        Write-Output "Process has already exited."
    }
  register: terminate_output
  when: minecraft_process_id.stdout is defined

- name: Display termination status
  debug:
    msg: "{{ terminate_output.stdout }}"
