---
- name: Check if JAVA_HOME environment variable is set
  ansible.windows.win_shell: "[System.Environment]::GetEnvironmentVariable('JAVA_HOME', 'Machine')"
  register: java_home_var
  changed_when: false

- name: Debug JAVA_HOME value
  debug:
    msg: "JAVA_HOME is set to: {{ java_home_var.stdout | default('Not Set') }}"

- block:
  - name: Get Java version on Windows
    raw: java -fullversion
    register: java_version_output

  - name: Debug Java version
    debug:
      msg: "Java version is set to: {{ java_version_output.stderr | default('Not Set') }}"

  - block:
    - name: Parse Java version
      set_fact:
        java_version: "{{ (java_version_output.stderr | regex_search('version \"([0-9]+)', '\\1')) | first }}"
    
    - name: Debug Parsed Java version
      debug:
        msg: "Parsed Java version is set to: {{ java_version | default('Not Set') }}"

    when: java_version_output.stderr is defined and java_version_output.stderr is defined
  when: java_home_var.stdout is defined and java_home_var.stdout != ''
