# roles/minecraft/tasks/port_forwarding.yml
---
# Configure Windows Firewall to allow Minecraft traffic on port 25565 (TCP)
- name: Configure Windows Firewall to allow Minecraft traffic on port 25565 (TCP)
  community.windows.win_firewall_rule:
    name: "Allow Minecraft Server TCP"
    localport: "25565"
    action: allow
    direction: in
    protocol: "TCP"
    enable: yes
    program: "{{ java_home_var.stdout }}\\bin\\javaw.exe"

# Configure Windows Firewall to allow Minecraft traffic on port 25565 (UDP)
- name: Configure Windows Firewall to allow Minecraft traffic on port 25565 (UDP)
  community.windows.win_firewall_rule:
    name: "Allow Minecraft Server UDP"
    localport: "25565"
    action: allow
    direction: in
    protocol: "UDP"
    enable: yes
    program: "{{ java_home_var.stdout }}\\bin\\javaw.exe"

- name: Retrieve external IP address using OpenDNS
  ansible.windows.win_shell: |
    nslookup myip.opendns.com resolver1.opendns.com | Select-String -Pattern "Address: " | Select-Object -Last 1
  register: external_ip_result

# Verify that gateway and dns_server variables are set correctly          
- name: Display retrieved network values for debugging
  ansible.builtin.debug:
    msg: "External ip result: {{ external_ip_result }}"

# Display static IP address and external IP address confirmation
- name: Display IP address confirmation
  ansible.builtin.debug:
    msg: |
      Minecraft server is configured with the static internal IP address {{ ansible_host }} on port 25565 for local connections.
      External IP address is {{ external_ip_result.stdout }} for external connections.

