# roles/minecraft/tasks/server_setup.yml
---
- name: Create Minecraft Server Directory
  win_file:
    path: "C:\\Minecraft"
    state: directory

- name: Download Minecraft Server .jar
  win_get_url:
    url: "https://launcher.mojang.com/v1/objects/<minecraft_server_version>/server.jar"
    dest: "C:\\Minecraft\\server.jar"
  register: minecraft_downloaded

- name: Verify Minecraft Server Download
  win_stat:
    path: "C:\\Minecraft\\server.jar"
  register: server_jar
  until: server_jar.stat.exists
  retries: 3
  delay: 10

- name: Accept EULA for Minecraft
  win_template:
    src: "eula.txt.j2"
    dest: "C:\\Minecraft\\eula.txt"
  vars:
    eula_value: true

